# Generated by Django 5.0.4 on 2026-03-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=18, verbose_name="CPF/CNPJ do importador"
                    ),
                ),
                (
                    "id_chave_encrypted",
                    models.TextField(verbose_name="ID da chave (criptografado)"),
                ),
                (
                    "chave_secreta_encrypted",
                    models.TextField(verbose_name="Chave secreta (criptografada)"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de API",
                "verbose_name_plural": "Configurações de API",
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="ConsultaDeclaracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DI", "DI (Declaração de Importação)"),
                            ("DUIMP", "DUIMP"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("numero", models.CharField(max_length=50, verbose_name="Número")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(blank=True, verbose_name="Mensagem de erro"),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="excels/",
                        verbose_name="Arquivo Excel",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID da tarefa Celery"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemDeclaracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_adicao", models.PositiveIntegerField(verbose_name="Nº Adição")),
                ("sequencial", models.PositiveIntegerField(verbose_name="Seq.")),
                (
                    "quantidade",
                    models.CharField(max_length=50, verbose_name="Quantidade"),
                ),
                (
                    "unidade_medida",
                    models.CharField(max_length=50, verbose_name="Unidade Medida"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição Mercadoria")),
                (
                    "c_class_trib",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="cClassTrib"
                    ),
                ),
                (
                    "valor_unitario",
                    models.CharField(max_length=50, verbose_name="Valor Unitário"),
                ),
                ("ii", models.CharField(max_length=20, verbose_name="II")),
                ("ipi", models.CharField(max_length=20, verbose_name="IPI")),
                (
                    "pis_pasep",
                    models.CharField(max_length=20, verbose_name="PIS/PASEP"),
                ),
                ("cofins", models.CharField(max_length=20, verbose_name="COFINS")),
                ("ncm", models.CharField(max_length=20, verbose_name="NCM")),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="declaracoes.consultadeclaracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
                "ordering": ["num_adicao", "sequencial"],
            },
        ),
    ]
